# SPDX-FileCopyrightText: © 2026 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
# Nginx Demo deployment - 1
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-demo-1"
  labels:
    app.kubernetes.io/name: "nginx-demo"
    app.kubernetes.io/instance: "nginx-demo-1"
    app.kubernetes.io/version: "3.13.1"
    app.kubernetes.io/component: "website"
    app: "nginx-demo-1"
    version: "3.13.1"
    msgidx: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "nginx-demo"
      app.kubernetes.io/instance: "nginx-demo-1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "nginx-demo"
        app.kubernetes.io/instance: "nginx-demo-1"
        app.kubernetes.io/version: "3.13.1"
        app.kubernetes.io/component: "website"
        app: "nginx-demo-1"
        version: "3.13.1"
        msgidx: "1"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: "nginx-tmp-1"
          emptyDir: {}
        - name: "nginx-tmp-2"
          emptyDir: {}
      containers:
        - name: "nginx-demo"
          image: "ghcr.io/clifford2/nginx-demo:3.13.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          startupProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 3
            initialDelaySeconds: 2
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "32Mi"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: "File"
          volumeMounts:
            - name: "nginx-tmp-1"
              mountPath: "/tmp"
            - name: "nginx-tmp-2"
              mountPath: "/usr/share/nginx/html"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: "RuntimeDefault"
          env:
            - name: "MESSAGE"
              value: "Ah, you're an outcast! That's great, so are we! - Timon"
---
# Nginx Demo deployment - 2
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-demo-2"
  labels:
    app.kubernetes.io/name: "nginx-demo"
    app.kubernetes.io/instance: "nginx-demo-2"
    app.kubernetes.io/version: "3.13.1"
    app.kubernetes.io/component: "website"
    app: "nginx-demo-2"
    version: "3.13.1"
    msgidx: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "nginx-demo"
      app.kubernetes.io/instance: "nginx-demo-2"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "nginx-demo"
        app.kubernetes.io/instance: "nginx-demo-2"
        app.kubernetes.io/version: "3.13.1"
        app.kubernetes.io/component: "website"
        app: "nginx-demo-2"
        version: "3.13.1"
        msgidx: "2"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: "nginx-tmp-1"
          emptyDir: {}
        - name: "nginx-tmp-2"
          emptyDir: {}
      containers:
        - name: "nginx-demo"
          image: "ghcr.io/clifford2/nginx-demo:3.13.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          startupProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 3
            initialDelaySeconds: 7
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "32Mi"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: "File"
          volumeMounts:
            - name: "nginx-tmp-1"
              mountPath: "/tmp"
            - name: "nginx-tmp-2"
              mountPath: "/usr/share/nginx/html"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: "RuntimeDefault"
          env:
            - name: "MESSAGE"
              value: "They call me Mr. Pig! - Puumba"
---
# Nginx Demo deployment - 3
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-demo-3"
  labels:
    app.kubernetes.io/name: "nginx-demo"
    app.kubernetes.io/instance: "nginx-demo-3"
    app.kubernetes.io/version: "3.13.1"
    app.kubernetes.io/component: "website"
    app: "nginx-demo-3"
    version: "3.13.1"
    msgidx: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "nginx-demo"
      app.kubernetes.io/instance: "nginx-demo-3"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "nginx-demo"
        app.kubernetes.io/instance: "nginx-demo-3"
        app.kubernetes.io/version: "3.13.1"
        app.kubernetes.io/component: "website"
        app: "nginx-demo-3"
        version: "3.13.1"
        msgidx: "3"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: "nginx-tmp-1"
          emptyDir: {}
        - name: "nginx-tmp-2"
          emptyDir: {}
      containers:
        - name: "nginx-demo"
          image: "ghcr.io/clifford2/nginx-demo:3.13.1"
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: "http"
              containerPort: 8080
              protocol: "TCP"
          startupProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 3
            initialDelaySeconds: 12
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: 8080
              path: "/healthz.json"
            failureThreshold: 2
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              memory: "16Mi"
            limits:
              memory: "32Mi"
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: "File"
          volumeMounts:
            - name: "nginx-tmp-1"
              mountPath: "/tmp"
            - name: "nginx-tmp-2"
              mountPath: "/usr/share/nginx/html"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - "ALL"
            seccompProfile:
              type: "RuntimeDefault"
          env:
            - name: "MESSAGE"
              value: "This is my kingdom. If I don't fight for it, who will? - Simba"
