# SPDX-FileCopyrightText: © 2024 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
# Kubernetes deployment for Nginx Demo - no COLOR set
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-nocolor
  labels:
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/instance: nginx-demo-nocolor
    app.kubernetes.io/version: 1.5.0
    app.kubernetes.io/component: website
    app: nginx-demo-nocolor
    version: 1.5.0
    color: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-demo
      app.kubernetes.io/instance: nginx-demo-nocolor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-demo
        app.kubernetes.io/instance: nginx-demo-nocolor
        app.kubernetes.io/version: 1.5.0
        app.kubernetes.io/component: website
        app: nginx-demo-nocolor
        version: 1.5.0
        color: default
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - name: nginx-demo
        image: ghcr.io/clifford2/nginx-demo:1.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        startupProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 10
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 5
          failureThreshold: 12
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 10
          failureThreshold: 2
          periodSeconds: 10
        resources:
          requests:
            memory: 16Mi
          limits:
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nginx-tmp-1
          mountPath: /tmp
        - name: nginx-tmp-2
          mountPath: /usr/share/nginx/html
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1234
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-tmp-1
        emptyDir: {}
      - name: nginx-tmp-2
        emptyDir: {}
---
# Nginx Demo deployment - Blue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-blue
  labels:
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/instance: nginx-demo-blue
    app.kubernetes.io/version: 1.5.0
    app.kubernetes.io/component: website
    app: nginx-demo-blue
    version: 1.5.0
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-demo
      app.kubernetes.io/instance: nginx-demo-blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-demo
        app.kubernetes.io/instance: nginx-demo-blue
        app.kubernetes.io/version: 1.5.0
        app.kubernetes.io/component: website
        app: nginx-demo-blue
        version: 1.5.0
        color: blue
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - name: nginx-demo
        image: ghcr.io/clifford2/nginx-demo:1.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: COLOR
          value: blue
        startupProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 10
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 5
          failureThreshold: 12
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 10
          failureThreshold: 2
          periodSeconds: 10
        resources:
          requests:
            memory: 16Mi
          limits:
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nginx-tmp-1
          mountPath: /tmp
        - name: nginx-tmp-2
          mountPath: /usr/share/nginx/html
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1234
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-tmp-1
        emptyDir: {}
      - name: nginx-tmp-2
        emptyDir: {}
---
# Nginx Demo deployment - Green
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-green
  labels:
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/instance: nginx-demo-green
    app.kubernetes.io/version: 1.5.0
    app.kubernetes.io/component: website
    app: nginx-demo-green
    version: 1.5.0
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-demo
      app.kubernetes.io/instance: nginx-demo-green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-demo
        app.kubernetes.io/instance: nginx-demo-green
        app.kubernetes.io/version: 1.5.0
        app.kubernetes.io/component: website
        app: nginx-demo-green
        version: 1.5.0
        color: green
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - name: nginx-demo
        image: ghcr.io/clifford2/nginx-demo:1.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: COLOR
          value: green
        startupProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 10
          failureThreshold: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 5
          failureThreshold: 12
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: 8080
            path: /index.json
          initialDelaySeconds: 10
          failureThreshold: 2
          periodSeconds: 10
        resources:
          requests:
            memory: 16Mi
          limits:
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: nginx-tmp-1
          mountPath: /tmp
        - name: nginx-tmp-2
          mountPath: /usr/share/nginx/html
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        fsGroup: 1234
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-tmp-1
        emptyDir: {}
      - name: nginx-tmp-2
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  labels:
    app.kubernetes.io/name: nginx-demo
    app.kubernetes.io/instance: nginx-demo
    app.kubernetes.io/component: website
    app: nginx-demo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: nginx-demo
  sessionAffinity: None
